services:
  postgres:
    image: postgres:17
    container_name: postgres-db
    restart: always
    env_file: ".env"
    volumes: 
      - pgdata:/var/lib/postgresql/data
    networks: 
      - backend
    ports: 
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  payment-app:
    build: .
    container_name: payment-app
    restart: always
    env_file: ".env"
    environment:
      - HOST=postgres
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8000:8000"
    networks:
      - backend

volumes:
  pgdata:

networks:
  backend:
    driver: bridge
