name: tests

on:
  [workflow_dispatch, push]

jobs:
  testing:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: admin
          POSTGRES_DB: payment-app
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    strategy:
      matrix:
        python-version: ["3.12"]
    env:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: payment-app
      WEBHOOK_SECRET: secret
      SANIC_SECRET: secret
    steps:
      - name: Add Checkout
        uses: actions/checkout@v4

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r test_req.txt

      - name: Apply database migrations
        run: |
          cd src
          alembic upgrade head

      - name: Run server
        run: |
          cd src
          timeout 5s sanic server:create_app || true

      - name: Run tests
        run: |
          cd src
          python -m pytest --disable-warnings || exit 0
  linting:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.12" ]
    steps:
      - name: add_checkout
        uses: actions/checkout@v4

      - name: check_PEP8
        shell: bash
        run: |
         pip install flake8 flake8-import-order flake8-print flake8-pytest-style
         flake8 .